### ISSUE TITLE
MySQL config does not accept localhost/127.0.0.1 as a valid host

### ISSUE THREAD

**Issue by mkody** [usefathom/fathom#56]
First of all, thanks to all contributors for this project!

I wanted to install Fathom on my server, but I'm getting a panic on start (see log below) when using MySQL. Leaving the defaults to SQLite works. 

I first tried with the release and then to build it myself, but I get the same results.
Then I changed `FATHOM_DATABASE_HOST` to `127.0.0.1` or the local IP, but no changes.

Here's my config (with changed user/pass):

```bash
FATHOM_DEBUG=true
FATHOM_SERVER_ADDR=9050
FATHOM_DATABASE_DRIVER="mysql"
FATHOM_DATABASE_NAME="fathom"
FATHOM_DATABASE_USER="fathom"
FATHOM_DATABASE_PASSWORD="NotAPassword"
FATHOM_DATABASE_HOST="localhost"
FATHOM_SECRET="NotASecret"
```

Here's the log:

```plain
root@Web:~# fathom --config=/root/fathom.env server
INFO[0000] Fathom 1.0.0                                 
INFO[0000] Configuration file: /root/fathom.env         
panic: default addr for network 'localhost' unknown
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x81bf5c]

goroutine 1 [running]:
main.after(0xc4200c4b00, 0xc420071988, 0x57e574)
        /go/src/github.com/usefathom/fathom/cmd/fathom/main.go:95 +0x2c
github.com/usefathom/fathom/vendor/github.com/urfave/cli.(*App).Run.func1(0xc420180000, 0xc4200c4b00, 0xc420071d40)
        /go/src/github.com/usefathom/fathom/vendor/github.com/urfave/cli/app.go:233 +0x3b
panic(0x9c7ee0, 0xc42017c620)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/usefathom/fathom/vendor/github.com/jmoiron/sqlx.MustConnect(0xc4200de7d7, 0x5, 0xc4200ce200, 0x39, 0x7ffc9bb2de10)
        /go/src/github.com/usefathom/fathom/vendor/github.com/jmoiron/sqlx/sqlx.go:652 +0x80
github.com/usefathom/fathom/pkg/datastore/sqlstore.New(0xc4200b0aa0, 0xc42017c1e0)
        /go/src/github.com/usefathom/fathom/pkg/datastore/sqlstore/sqlstore.go:26 +0x5d
github.com/usefathom/fathom/pkg/datastore.New(0xc4200b0aa0, 0x10, 0xc42013f240)
        /go/src/github.com/usefathom/fathom/pkg/datastore/datastore.go:59 +0x2b
main.before(0xc4200c4b00, 0xa81b40, 0xc420180000)
        /go/src/github.com/usefathom/fathom/cmd/fathom/main.go:90 +0x93
github.com/usefathom/fathom/vendor/github.com/urfave/cli.(*App).Run(0xc420180000, 0xc4200a4060, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/usefathom/fathom/vendor/github.com/urfave/cli/app.go:244 +0x738
main.main()
        /go/src/github.com/usefathom/fathom/cmd/fathom/main.go:80 +0x8c1
```

**Comment by dannyvankooten** [comment]
Hey @mkody, can you try with an empty string instead of a local address?

Still something to fix, but I'd like to check whether my theory is right.

**Comment by mkody** [comment]
Yes, that worked and I now see tables.

Only got an error but that's an another problem I guess.

```plain
root@Web:~/fathom# fathom server
INFO[0000] Fathom 1.0.0                                 
INFO[0000] Configuration file: /root/fathom/.env        
INFO[0000] Connected to mysql database: fathom          
ERRO[0004] Error applying database migrations: Error 1071: Specified key was too long; max key length is 767 bytes handling 1_initial_tables.sql 
INFO[0004] Server is now listening on :9050 
```

**Comment by dannyvankooten** [comment]
Awesome, thanks. Apparently this is due to the default charset being utf8mb4 which limits our column length to 767/4=191 characters if we want to have an index (key) on these columns.

Changing your default charset before attempting to run the migration will probably work as a workaround, but we should probably explicitly set the charset we'd like to use in our `CREATE TABLE` statements.

**Comment by mkody** [comment]
I recreated the database and set the charset to `utf8_general_ci` and it works, thanks!
