### ISSUE TITLE
How to specify SQL Database FATHOM_DATABASE_HOST

### ISSUE THREAD

**Issue by r-chris** [usefathom/fathom#60]
I am not able to reach a (MariaDB) SQL Database, when setting the `FATHOM_DATABASE_HOST` and couldn't determine from the wiki documentation what the `FATHOM_DATABASE_HOST` expects exactly. I am seeing the error below. As you can see I am getting:

**`ERR panic: default addr for network 'galera-service.service.consul' unknown`**

```
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR time="2018-06-12T14:35:07Z" level=info msg="Fathom 1.0.0"
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR time="2018-06-12T14:35:07Z" level=warning msg="Missing configuration file. Using defaults."
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR panic: default addr for network 'galera-service.service.consul' unknown
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR panic: runtime error: invalid memory address or nil pointer dereference
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x819aac]
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR goroutine 1 [running]:
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR main.after(0xc4200ca9a0, 0xc420079988, 0x57af44)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/cmd/fathom/main.go:95 +0x2c
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR github.com/usefathom/fathom/vendor/github.com/urfave/cli.(*App).Run.func1(0xc420300000, 0xc4200ca9a0, 0xc420079d40)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/vendor/github.com/urfave/cli/app.go:233 +0x3b
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR panic(0x9ccaa0, 0xc420184550)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /usr/local/go/src/runtime/panic.go:502 +0x229
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR github.com/usefathom/fathom/vendor/github.com/jmoiron/sqlx.MustConnect(0xc420026057, 0x5, 0xc420306000, 0x88, 0xa64b08)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/vendor/github.com/jmoiron/sqlx/sqlx.go:652 +0x80
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR github.com/usefathom/fathom/pkg/datastore/sqlstore.New(0xc4200b8a00, 0x4)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/pkg/datastore/sqlstore/sqlstore.go:26 +0x5d
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR github.com/usefathom/fathom/pkg/datastore.New(0xc4200b8a00, 0x4, 0xc42012f480)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/pkg/datastore/datastore.go:59 +0x2b
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR main.before(0xc4200ca9a0, 0xb54ee8, 0xc420300000)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/cmd/fathom/main.go:90 +0x93
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR github.com/usefathom/fathom/vendor/github.com/urfave/cli.(*App).Run(0xc420300000, 0xc4200bc000, 0x2, 0x2, 0x0, 0x0)
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/vendor/github.com/urfave/cli/app.go:244 +0x738
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR main.main()
2018-06-12 16:35:07 [APP/PROC/WEB/0] ERR /go/src/github.com/usefathom/fathom/cmd/fathom/main.go:80 +0x8c1
```

Any idea why I can't connect to that DB?

**Comment by mkody** [comment]
Yes, take a look at #56. (You just made a duplicate.)

**Comment by r-chris** [comment]
@mkody Thank you for pointing that out. Actually, I read #56 and I didn't consider this a duplicate. You tried to connect to a MySQL Server running on localhost. I am not trying to do that (and also not specifying the host name wouldn't work on my case, since the SQL database is actually not on the same instance).

**Comment by dannyvankooten** [comment]
Hey @r-chris,

I think currently something is going wrong in putting together the [dsn connection string](https://github.com/usefathom/fathom/blob/master/pkg/datastore/sqlstore/config.go#L20) for MySQL databases when not using an empty string (indicating localhost). I'll investigate as soon as I get a chance.

**Comment by r-chris** [comment]
Thanks - ok in that case if you do see this as a duplicate of #56 - feel free to close this issue!
